version: '2'
services:
    s_tracking-app:
        image: s_tracking
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://s_tracking-mysql:3306/s_tracking?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    s_tracking-mysql:
        extends:
            file: mysql.yml
            service: s_tracking-mysql
